# Generated by Django 2.2 on 2021-08-12 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(1, 1, 1)),
            preserve_default=False,
        ),
    ]
