# Generated by Django 2.2 on 2021-08-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_user_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='updated_ate',
            new_name='updated_at',
        ),
    ]
